version: '3'
services:
  database:
    image: mysql
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./:/docker-entrypoint-initdb.d

    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root


-- Arquivo: create_database.sql

-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS curso_typeorm;

-- Definindo o banco de dados criado como o ativo
USE curso_typeorm;